ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Overview
This project started out as a simple experiment with Spring's new structured logging support but ended up morphing into an example of how to add custom ServiceConnection support to your tests.

== Prerequisites
* JDK 21 or greater
* Maven, if you don't want to use the provided wrapper for some reason.

== Building
* `./mvnw --batch-mode --update-snapshots --errors clean install`

== Installation
This is just a couple of tests, so there is nothing to install.

== Tips and Tricks
=== Basic Recipe
To enable a container unknown to Spring's ServiceConnection annotation, we need to follow these steps:

. create an interface the extends `ConnectionDetails`, a marker interface that tells Spring where to look for connection properties, adding whatever connection properties needed to connect to the container
. implement that interface in an object that extends `ContainerConnectionDetailsFactory`, which Spring will use to populate the appropriate connection bean, e.g. `RestClient`
. register the factory in `META-INF/spring.factories`, telling Spring it should run the specified factories at test time.

=== Objects of Interest
* `CustomServiceConnectionTests` to see everything working together
* `WireMockContainerConnectionDetailsFactory` to see how a RestClient is configured to talk to WireMock
* `CustomVaultContainerConnectionDetailsFactory` to how a VaultTemplate is configured to talk to Vault
* `src/test/resources/META-INF/spring.factories` to see what the factory registration looks like

== Troubleshooting

== Contributing

== License and Credits
* This project is licensed under the http://www.apache.org/licenses/[Apache License Version 2.0, January 2004].
* https://www.docker.com/blog/building-spring-boots-serviceconnection-for-testcontainers-wiremock/[Building Spring Boot’s ServiceConnection for Testcontainers WireMock] was the inspiration for this example
* https://spring.io/blog/2023/06/23/improved-testcontainers-support-in-spring-boot-3-1[Improved Testcontainers Support in Spring Boot 3.1] to learn all about Spring's awesome Testcontainer support
